#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void thread_weight_deliver 
    (__po_hi_request_t* request);

void* thread_weight_job (void);

void thread_height_deliver 
    (__po_hi_request_t* request);

void* thread_height_job (void);

void thread_rotor_deliver 
    (__po_hi_request_t* request);

void* thread_rotor_job (void);

void thread_radar_deliver 
    (__po_hi_request_t* request);

void* thread_radar_job (void);

void thread_gps_deliver 
    (__po_hi_request_t* request);

void* thread_gps_job (void);

void thread_set_target_deliver 
    (__po_hi_request_t* request);

void* thread_set_target_job (void);

void thread_analyse_data_deliver 
    (__po_hi_request_t* request);

void* thread_analyse_data_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
