#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <types.h>
#include "subprograms.h"
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_thread_weight_weight_out_local_destinations[1] = {thread_analyse_data_global_weight_in};
__po_hi_uint8_t __po_hi_thread_weight_woffsets[__po_hi_thread_weight_nb_ports];
__po_hi_uint8_t __po_hi_thread_weight_offsets[__po_hi_thread_weight_nb_ports];
__po_hi_uint8_t __po_hi_thread_weight_used_size[__po_hi_thread_weight_nb_ports];
__po_hi_uint8_t __po_hi_thread_weight_empties[__po_hi_thread_weight_nb_ports];
__po_hi_uint8_t __po_hi_thread_weight_first[__po_hi_thread_weight_nb_ports];
__po_hi_request_t __po_hi_thread_weight_recent[__po_hi_thread_weight_nb_ports];
__po_hi_port_t __po_hi_thread_weight_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_weight_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_thread_weight_history[0];
__po_hi_uint8_t __po_hi_thread_weight_n_dest[__po_hi_thread_weight_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_thread_weight_fifo_size[__po_hi_thread_weight_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_thread_weight_destinations[__po_hi_thread_weight_nb_ports] = {NULL,__po_hi_thread_weight_weight_out_local_destinations};

/*!
 * \fn void thread_weight_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_weight
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_weight_deliver) stores the incoming request for the 
 * taskthread_weight
 */
void thread_weight_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_weight_global_weight_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_weight_k, thread_weight_local_weight_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_weight_job (void)
 * \brief Function executed by the task thread_weight
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_weight*/
/*  Get the IN ports values*/
void* thread_weight_job (void)
{
  __po_hi_request_t static weight_in_request;
  base_types__float weight_out_request_var;
  __po_hi_request_t weight_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_weight_k, __po_hi_thread_weight_nb_ports, __po_hi_thread_weight_queue, __po_hi_thread_weight_fifo_size, __po_hi_thread_weight_first, __po_hi_thread_weight_offsets, __po_hi_thread_weight_woffsets, __po_hi_thread_weight_n_dest, __po_hi_thread_weight_destinations, __po_hi_thread_weight_used_size, __po_hi_thread_weight_history, __po_hi_thread_weight_recent, __po_hi_thread_weight_empties, __po_hi_thread_weight_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_weight_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_weight_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_weight_k, thread_weight_local_weight_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_weight_k, thread_weight_local_weight_in, &(weight_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_weight_k, thread_weight_local_weight_in);

    }
    /*  Call implementation*/
    drone__readweight_spg (weight_in_request.vars.thread_weight_global_weight_in.thread_weight_global_weight_in, &(weight_out_request_var));
    /*  Set the OUT port values*/
    weight_out_request.vars.thread_weight_global_weight_out.thread_weight_global_weight_out = weight_out_request_var;
    weight_out_request.port = thread_weight_global_weight_out;
    __po_hi_gqueue_store_out (the_controller_thread_weight_k, thread_weight_local_weight_out, &(weight_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_weight_k, thread_weight_global_weight_out);
    __po_hi_wait_for_next_period (the_controller_thread_weight_k);
  }
}

__po_hi_port_t __po_hi_thread_height_height_out_local_destinations[1] = {thread_analyse_data_global_height_in};
__po_hi_uint8_t __po_hi_thread_height_woffsets[__po_hi_thread_height_nb_ports];
__po_hi_uint8_t __po_hi_thread_height_offsets[__po_hi_thread_height_nb_ports];
__po_hi_uint8_t __po_hi_thread_height_used_size[__po_hi_thread_height_nb_ports];
__po_hi_uint8_t __po_hi_thread_height_empties[__po_hi_thread_height_nb_ports];
__po_hi_uint8_t __po_hi_thread_height_first[__po_hi_thread_height_nb_ports];
__po_hi_request_t __po_hi_thread_height_recent[__po_hi_thread_height_nb_ports];
__po_hi_port_t __po_hi_thread_height_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_height_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_thread_height_history[0];
__po_hi_uint8_t __po_hi_thread_height_n_dest[__po_hi_thread_height_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_thread_height_fifo_size[__po_hi_thread_height_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_thread_height_destinations[__po_hi_thread_height_nb_ports] = {NULL,__po_hi_thread_height_height_out_local_destinations};

/*!
 * \fn void thread_height_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_height
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_height_deliver) stores the incoming request for the 
 * taskthread_height
 */
void thread_height_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_height_global_height_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_height_k, thread_height_local_height_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_height_job (void)
 * \brief Function executed by the task thread_height
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_height*/
/*  Get the IN ports values*/
void* thread_height_job (void)
{
  __po_hi_request_t static height_in_request;
  base_types__float height_out_request_var;
  __po_hi_request_t height_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_height_k, __po_hi_thread_height_nb_ports, __po_hi_thread_height_queue, __po_hi_thread_height_fifo_size, __po_hi_thread_height_first, __po_hi_thread_height_offsets, __po_hi_thread_height_woffsets, __po_hi_thread_height_n_dest, __po_hi_thread_height_destinations, __po_hi_thread_height_used_size, __po_hi_thread_height_history, __po_hi_thread_height_recent, __po_hi_thread_height_empties, __po_hi_thread_height_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_height_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_height_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_height_k, thread_height_local_height_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_height_k, thread_height_local_height_in, &(height_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_height_k, thread_height_local_height_in);

    }
    /*  Call implementation*/
    drone__readheight_spg (height_in_request.vars.thread_height_global_height_in.thread_height_global_height_in, &(height_out_request_var));
    /*  Set the OUT port values*/
    height_out_request.vars.thread_height_global_height_out.thread_height_global_height_out = height_out_request_var;
    height_out_request.port = thread_height_global_height_out;
    __po_hi_gqueue_store_out (the_controller_thread_height_k, thread_height_local_height_out, &(height_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_height_k, thread_height_global_height_out);
    __po_hi_wait_for_next_period (the_controller_thread_height_k);
  }
}

__po_hi_port_t __po_hi_thread_rotor_rotor_power_out_local_destinations[1] = {thread_analyse_data_global_rotor_power_in};
__po_hi_uint8_t __po_hi_thread_rotor_woffsets[__po_hi_thread_rotor_nb_ports];
__po_hi_uint8_t __po_hi_thread_rotor_offsets[__po_hi_thread_rotor_nb_ports];
__po_hi_uint8_t __po_hi_thread_rotor_used_size[__po_hi_thread_rotor_nb_ports];
__po_hi_uint8_t __po_hi_thread_rotor_empties[__po_hi_thread_rotor_nb_ports];
__po_hi_uint8_t __po_hi_thread_rotor_first[__po_hi_thread_rotor_nb_ports];
__po_hi_request_t __po_hi_thread_rotor_recent[__po_hi_thread_rotor_nb_ports];
__po_hi_port_t __po_hi_thread_rotor_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_rotor_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_thread_rotor_history[0];
__po_hi_uint8_t __po_hi_thread_rotor_n_dest[__po_hi_thread_rotor_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_thread_rotor_fifo_size[__po_hi_thread_rotor_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_thread_rotor_destinations[__po_hi_thread_rotor_nb_ports] = {NULL,__po_hi_thread_rotor_rotor_power_out_local_destinations};

/*!
 * \fn void thread_rotor_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_rotor
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_rotor_deliver) stores the incoming request for the taskthread_rotor
 */
void thread_rotor_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_rotor_global_rotor_power_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_rotor_k, thread_rotor_local_rotor_power_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_rotor_job (void)
 * \brief Function executed by the task thread_rotor
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_rotor*/
/*  Get the IN ports values*/
void* thread_rotor_job (void)
{
  __po_hi_request_t static rotor_power_in_request;
  base_types__float rotor_power_out_request_var;
  __po_hi_request_t rotor_power_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_rotor_k, __po_hi_thread_rotor_nb_ports, __po_hi_thread_rotor_queue, __po_hi_thread_rotor_fifo_size, __po_hi_thread_rotor_first, __po_hi_thread_rotor_offsets, __po_hi_thread_rotor_woffsets, __po_hi_thread_rotor_n_dest, __po_hi_thread_rotor_destinations, __po_hi_thread_rotor_used_size, __po_hi_thread_rotor_history, __po_hi_thread_rotor_recent, __po_hi_thread_rotor_empties, __po_hi_thread_rotor_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_rotor_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_rotor_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_rotor_k, thread_rotor_local_rotor_power_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_rotor_k, thread_rotor_local_rotor_power_in, &(rotor_power_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_rotor_k, thread_rotor_local_rotor_power_in);

    }
    /*  Call implementation*/
    drone__rotorpower_spg (rotor_power_in_request.vars.thread_rotor_global_rotor_power_in.thread_rotor_global_rotor_power_in, &(rotor_power_out_request_var));
    /*  Set the OUT port values*/
    rotor_power_out_request.vars.thread_rotor_global_rotor_power_out.thread_rotor_global_rotor_power_out = rotor_power_out_request_var;
    rotor_power_out_request.port = thread_rotor_global_rotor_power_out;
    __po_hi_gqueue_store_out (the_controller_thread_rotor_k, thread_rotor_local_rotor_power_out, &(rotor_power_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_rotor_k, thread_rotor_global_rotor_power_out);
    __po_hi_wait_for_next_period (the_controller_thread_rotor_k);
  }
}

__po_hi_port_t __po_hi_thread_radar_blockade_out_local_destinations[1] = {thread_analyse_data_global_blockade_in};
__po_hi_uint8_t __po_hi_thread_radar_woffsets[__po_hi_thread_radar_nb_ports];
__po_hi_uint8_t __po_hi_thread_radar_offsets[__po_hi_thread_radar_nb_ports];
__po_hi_uint8_t __po_hi_thread_radar_used_size[__po_hi_thread_radar_nb_ports];
__po_hi_uint8_t __po_hi_thread_radar_empties[__po_hi_thread_radar_nb_ports];
__po_hi_uint8_t __po_hi_thread_radar_first[__po_hi_thread_radar_nb_ports];
__po_hi_request_t __po_hi_thread_radar_recent[__po_hi_thread_radar_nb_ports];
__po_hi_port_t __po_hi_thread_radar_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_radar_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_thread_radar_history[16];
__po_hi_uint8_t __po_hi_thread_radar_n_dest[__po_hi_thread_radar_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_thread_radar_fifo_size[__po_hi_thread_radar_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_thread_radar_destinations[__po_hi_thread_radar_nb_ports] = {NULL,__po_hi_thread_radar_blockade_out_local_destinations};

/*!
 * \fn void thread_radar_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_radar
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_radar_deliver) stores the incoming request for the taskthread_radar
 */
void thread_radar_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_radar_global_blockade_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_radar_k, thread_radar_local_blockade_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_radar_job (void)
 * \brief Function executed by the task thread_radar
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_radar*/
/*  Get the IN ports values*/
void* thread_radar_job (void)
{
  __po_hi_request_t static blockade_in_request;
  base_types__float blockade_out_request_var;
  __po_hi_request_t blockade_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_radar_k, __po_hi_thread_radar_nb_ports, __po_hi_thread_radar_queue, __po_hi_thread_radar_fifo_size, __po_hi_thread_radar_first, __po_hi_thread_radar_offsets, __po_hi_thread_radar_woffsets, __po_hi_thread_radar_n_dest, __po_hi_thread_radar_destinations, __po_hi_thread_radar_used_size, __po_hi_thread_radar_history, __po_hi_thread_radar_recent, __po_hi_thread_radar_empties, __po_hi_thread_radar_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_radar_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_radar_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_radar_k, thread_radar_local_blockade_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_radar_k, thread_radar_local_blockade_in, &(blockade_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_radar_k, thread_radar_local_blockade_in);

    }
    /*  Call implementation*/
    drone__scanarea_spg (blockade_in_request.vars.thread_radar_global_blockade_in.thread_radar_global_blockade_in, &(blockade_out_request_var));
    /*  Set the OUT port values*/
    blockade_out_request.vars.thread_radar_global_blockade_out.thread_radar_global_blockade_out = blockade_out_request_var;
    blockade_out_request.port = thread_radar_global_blockade_out;
    __po_hi_gqueue_store_out (the_controller_thread_radar_k, thread_radar_local_blockade_out, &(blockade_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_radar_k, thread_radar_global_blockade_out);
    __po_hi_wait_for_next_period (the_controller_thread_radar_k);
  }
}

__po_hi_port_t __po_hi_thread_gps_location_out_local_destinations[2] = {the_aerial_global_location_out,thread_analyse_data_global_location_in};
__po_hi_uint8_t __po_hi_thread_gps_woffsets[__po_hi_thread_gps_nb_ports];
__po_hi_uint8_t __po_hi_thread_gps_offsets[__po_hi_thread_gps_nb_ports];
__po_hi_uint8_t __po_hi_thread_gps_used_size[__po_hi_thread_gps_nb_ports];
__po_hi_uint8_t __po_hi_thread_gps_empties[__po_hi_thread_gps_nb_ports];
__po_hi_uint8_t __po_hi_thread_gps_first[__po_hi_thread_gps_nb_ports];
__po_hi_request_t __po_hi_thread_gps_recent[__po_hi_thread_gps_nb_ports];
__po_hi_port_t __po_hi_thread_gps_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_gps_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_thread_gps_history[0];
__po_hi_uint8_t __po_hi_thread_gps_n_dest[__po_hi_thread_gps_nb_ports] = {0,2};
__po_hi_int8_t __po_hi_thread_gps_fifo_size[__po_hi_thread_gps_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_thread_gps_destinations[__po_hi_thread_gps_nb_ports] = {NULL,__po_hi_thread_gps_location_out_local_destinations};

/*!
 * \fn void thread_gps_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_gps
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_gps_deliver) stores the incoming request for the taskthread_gps
 */
void thread_gps_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_gps_global_location_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_gps_k, thread_gps_local_location_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_gps_job (void)
 * \brief Function executed by the task thread_gps
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_gps*/
/*  Get the IN ports values*/
void* thread_gps_job (void)
{
  __po_hi_request_t static location_in_request;
  base_types__float location_out_request_var;
  __po_hi_request_t location_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_gps_k, __po_hi_thread_gps_nb_ports, __po_hi_thread_gps_queue, __po_hi_thread_gps_fifo_size, __po_hi_thread_gps_first, __po_hi_thread_gps_offsets, __po_hi_thread_gps_woffsets, __po_hi_thread_gps_n_dest, __po_hi_thread_gps_destinations, __po_hi_thread_gps_used_size, __po_hi_thread_gps_history, __po_hi_thread_gps_recent, __po_hi_thread_gps_empties, __po_hi_thread_gps_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_gps_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_gps_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_gps_k, thread_gps_local_location_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_gps_k, thread_gps_local_location_in, &(location_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_gps_k, thread_gps_local_location_in);

    }
    /*  Call implementation*/
    drone__gpsdata_spg (location_in_request.vars.thread_gps_global_location_in.thread_gps_global_location_in, &(location_out_request_var));
    /*  Set the OUT port values*/
    location_out_request.vars.thread_gps_global_location_out.thread_gps_global_location_out = location_out_request_var;
    location_out_request.port = thread_gps_global_location_out;
    __po_hi_gqueue_store_out (the_controller_thread_gps_k, thread_gps_local_location_out, &(location_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_gps_k, thread_gps_global_location_out);
    __po_hi_wait_for_next_period (the_controller_thread_gps_k);
  }
}

__po_hi_port_t __po_hi_thread_set_target_new_target_out_local_destinations[1] = {thread_analyse_data_global_new_target};
__po_hi_uint8_t __po_hi_thread_set_target_woffsets[__po_hi_thread_set_target_nb_ports];
__po_hi_uint8_t __po_hi_thread_set_target_offsets[__po_hi_thread_set_target_nb_ports];
__po_hi_uint8_t __po_hi_thread_set_target_used_size[__po_hi_thread_set_target_nb_ports];
__po_hi_uint8_t __po_hi_thread_set_target_empties[__po_hi_thread_set_target_nb_ports];
__po_hi_uint8_t __po_hi_thread_set_target_first[__po_hi_thread_set_target_nb_ports];
__po_hi_request_t __po_hi_thread_set_target_recent[__po_hi_thread_set_target_nb_ports];
__po_hi_port_t __po_hi_thread_set_target_queue[16 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_set_target_total_fifo_size = 16;
__po_hi_local_port_t __po_hi_thread_set_target_history[16];
__po_hi_uint8_t __po_hi_thread_set_target_n_dest[__po_hi_thread_set_target_nb_ports] = {0,1};
__po_hi_int8_t __po_hi_thread_set_target_fifo_size[__po_hi_thread_set_target_nb_ports] = {16,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_thread_set_target_destinations[__po_hi_thread_set_target_nb_ports] = {NULL,__po_hi_thread_set_target_new_target_out_local_destinations};

/*!
 * \fn void thread_set_target_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_set_target
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_set_target_deliver) stores the incoming request for the 
 * taskthread_set_target
 */
void thread_set_target_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_set_target_global_new_target_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_set_target_k, thread_set_target_local_new_target_in, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_set_target_job (void)
 * \brief Function executed by the task thread_set_target
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_set_target*/
/*  Get the IN ports values*/
void* thread_set_target_job (void)
{
  __po_hi_request_t static new_target_in_request;
  base_types__float new_target_out_request_var;
  __po_hi_request_t new_target_out_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_set_target_k, __po_hi_thread_set_target_nb_ports, __po_hi_thread_set_target_queue, __po_hi_thread_set_target_fifo_size, __po_hi_thread_set_target_first, __po_hi_thread_set_target_offsets, __po_hi_thread_set_target_woffsets, __po_hi_thread_set_target_n_dest, __po_hi_thread_set_target_destinations, __po_hi_thread_set_target_used_size, __po_hi_thread_set_target_history, __po_hi_thread_set_target_recent, __po_hi_thread_set_target_empties, __po_hi_thread_set_target_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_set_target_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_set_target_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_set_target_k, thread_set_target_local_new_target_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_set_target_k, thread_set_target_local_new_target_in, &(new_target_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_set_target_k, thread_set_target_local_new_target_in);

    }
    /*  Call implementation*/
    drone__setnewtarget_spg (new_target_in_request.vars.thread_set_target_global_new_target_in.thread_set_target_global_new_target_in, &(new_target_out_request_var));
    /*  Set the OUT port values*/
    new_target_out_request.vars.thread_set_target_global_new_target_out.thread_set_target_global_new_target_out = new_target_out_request_var;
    new_target_out_request.port = thread_set_target_global_new_target_out;
    __po_hi_gqueue_store_out (the_controller_thread_set_target_k, thread_set_target_local_new_target_out, &(new_target_out_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_set_target_k, thread_set_target_global_new_target_out);
    __po_hi_wait_for_next_period (the_controller_thread_set_target_k);
  }
}

__po_hi_port_t __po_hi_thread_analyse_data_rotor_power_out_local_destinations[1] = {the_drone_rotor_global_rotor_power_in};
__po_hi_port_t __po_hi_thread_analyse_data_status_change_local_destinations[1] = {the_aerial_global_status_change};
__po_hi_uint8_t __po_hi_thread_analyse_data_woffsets[__po_hi_thread_analyse_data_nb_ports];
__po_hi_uint8_t __po_hi_thread_analyse_data_offsets[__po_hi_thread_analyse_data_nb_ports];
__po_hi_uint8_t __po_hi_thread_analyse_data_used_size[__po_hi_thread_analyse_data_nb_ports];
__po_hi_uint8_t __po_hi_thread_analyse_data_empties[__po_hi_thread_analyse_data_nb_ports];
__po_hi_uint8_t __po_hi_thread_analyse_data_first[__po_hi_thread_analyse_data_nb_ports];
__po_hi_request_t __po_hi_thread_analyse_data_recent[__po_hi_thread_analyse_data_nb_ports];
__po_hi_port_t __po_hi_thread_analyse_data_queue[32 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_thread_analyse_data_total_fifo_size = 32;
__po_hi_local_port_t __po_hi_thread_analyse_data_history[32];
__po_hi_uint8_t __po_hi_thread_analyse_data_n_dest[__po_hi_thread_analyse_data_nb_ports] = {0,0,0,1,0,0,1,0};
__po_hi_int8_t __po_hi_thread_analyse_data_fifo_size[__po_hi_thread_analyse_data_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_INDATA,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_INDATA,16,__PO_HI_GQUEUE_FIFO_OUT,16};
__po_hi_port_t* __po_hi_thread_analyse_data_destinations[__po_hi_thread_analyse_data_nb_ports] = {NULL,NULL,NULL,__po_hi_thread_analyse_data_rotor_power_out_local_destinations,NULL,NULL,__po_hi_thread_analyse_data_status_change_local_destinations,NULL};

/*!
 * \fn void thread_analyse_data_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task thread_analyse_data
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (thread_analyse_data_deliver) stores the incoming request for the 
 * taskthread_analyse_data
 */
void thread_analyse_data_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case thread_analyse_data_global_location_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_analyse_data_k, thread_analyse_data_local_location_in, request);

      break;
    }
    case thread_analyse_data_global_height_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_analyse_data_k, thread_analyse_data_local_height_in, request);

      break;
    }
    case thread_analyse_data_global_weight_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_analyse_data_k, thread_analyse_data_local_weight_in, request);

      break;
    }
    case thread_analyse_data_global_rotor_power_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_analyse_data_k, thread_analyse_data_local_rotor_power_in, request);

      break;
    }
    case thread_analyse_data_global_blockade_in:
    {
      __po_hi_gqueue_store_in (the_controller_thread_analyse_data_k, thread_analyse_data_local_blockade_in, request);

      break;
    }
    case thread_analyse_data_global_new_target:
    {
      __po_hi_gqueue_store_in (the_controller_thread_analyse_data_k, thread_analyse_data_local_new_target, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* thread_analyse_data_job (void)
 * \brief Function executed by the task thread_analyse_data
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : thread_analyse_data*/
/*  Get the IN ports values*/
void* thread_analyse_data_job (void)
{
  __po_hi_request_t static location_in_request;
  __po_hi_request_t static height_in_request;
  __po_hi_request_t static weight_in_request;
  __po_hi_request_t static rotor_power_in_request;
  __po_hi_request_t static blockade_in_request;
  __po_hi_request_t static new_target_request;
  base_types__float rotor_power_out_request_var;
  base_types__float status_out_request_var;
  __po_hi_request_t rotor_power_out_request;
  __po_hi_request_t status_change_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (the_controller_thread_analyse_data_k, __po_hi_thread_analyse_data_nb_ports, __po_hi_thread_analyse_data_queue, __po_hi_thread_analyse_data_fifo_size, __po_hi_thread_analyse_data_first, __po_hi_thread_analyse_data_offsets, __po_hi_thread_analyse_data_woffsets, __po_hi_thread_analyse_data_n_dest, __po_hi_thread_analyse_data_destinations, __po_hi_thread_analyse_data_used_size, __po_hi_thread_analyse_data_history, __po_hi_thread_analyse_data_recent, __po_hi_thread_analyse_data_empties, __po_hi_thread_analyse_data_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (the_controller_thread_analyse_data_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (the_controller_thread_analyse_data_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_analyse_data_k, thread_analyse_data_local_location_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_location_in, &(location_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_location_in);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_analyse_data_k, thread_analyse_data_local_height_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_height_in, &(height_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_height_in);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_analyse_data_k, thread_analyse_data_local_weight_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_weight_in, &(weight_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_weight_in);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_analyse_data_k, thread_analyse_data_local_rotor_power_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_rotor_power_in, &(rotor_power_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_rotor_power_in);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_analyse_data_k, thread_analyse_data_local_blockade_in))
    {
          __po_hi_gqueue_get_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_blockade_in, &(blockade_in_request));
      __po_hi_gqueue_next_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_blockade_in);

    }
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (the_controller_thread_analyse_data_k, thread_analyse_data_local_new_target))
    {
          __po_hi_gqueue_get_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_new_target, &(new_target_request));
      __po_hi_gqueue_next_value (the_controller_thread_analyse_data_k, thread_analyse_data_local_new_target);

    }
    /*  Call implementation*/
    drone__analysedata_spg (location_in_request.vars.thread_analyse_data_global_location_in.thread_analyse_data_global_location_in, height_in_request.vars.thread_analyse_data_global_height_in.thread_analyse_data_global_height_in, weight_in_request.vars.thread_analyse_data_global_weight_in.thread_analyse_data_global_weight_in, &(rotor_power_out_request_var), rotor_power_in_request.vars.thread_analyse_data_global_rotor_power_in.thread_analyse_data_global_rotor_power_in, new_target_request.vars.thread_analyse_data_global_new_target.thread_analyse_data_global_new_target, blockade_in_request.vars.thread_analyse_data_global_blockade_in.thread_analyse_data_global_blockade_in, &(status_out_request_var));
    /*  Set the OUT port values*/
    rotor_power_out_request.vars.thread_analyse_data_global_rotor_power_out.thread_analyse_data_global_rotor_power_out = rotor_power_out_request_var;
    rotor_power_out_request.port = thread_analyse_data_global_rotor_power_out;
    __po_hi_gqueue_store_out (the_controller_thread_analyse_data_k, thread_analyse_data_local_rotor_power_out, &(rotor_power_out_request));
    status_change_request.vars.thread_analyse_data_global_status_change.thread_analyse_data_global_status_change = status_change_request_var;
    status_change_request.port = thread_analyse_data_global_status_change;
    __po_hi_gqueue_store_out (the_controller_thread_analyse_data_k, thread_analyse_data_local_status_change, &(status_change_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (the_controller_thread_analyse_data_k, thread_analyse_data_global_rotor_power_out);
    error =
     __po_hi_send_output (the_controller_thread_analyse_data_k, thread_analyse_data_global_status_change);
    __po_hi_wait_for_next_period (the_controller_thread_analyse_data_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case the_controller_thread_weight_k_entity:
    {
      thread_weight_deliver (request);

      break;
    }
    case the_controller_thread_height_k_entity:
    {
      thread_height_deliver (request);

      break;
    }
    case the_controller_thread_rotor_k_entity:
    {
      thread_rotor_deliver (request);

      break;
    }
    case the_controller_thread_radar_k_entity:
    {
      thread_radar_deliver (request);

      break;
    }
    case the_controller_thread_gps_k_entity:
    {
      thread_gps_deliver (request);

      break;
    }
    case the_controller_thread_set_target_k_entity:
    {
      thread_set_target_deliver (request);

      break;
    }
    case the_controller_thread_analyse_data_k_entity:
    {
      thread_analyse_data_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


