#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_float 
    (base_types__float value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_float (value, message, offset);
}

void __po_hi_unmarshall_type_float 
    (base_types__float* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_float (value, message, offset);
}

void __po_hi_marshall_request_thread_weight_weight_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_weight_global_weight_in.thread_weight_global_weight_in, message, offset);
}

void __po_hi_unmarshall_request_thread_weight_weight_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_weight_global_weight_in.thread_weight_global_weight_in), message, offset);
}

void __po_hi_marshall_request_thread_weight_weight_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_weight_global_weight_out.thread_weight_global_weight_out, message, offset);
}

void __po_hi_unmarshall_request_thread_weight_weight_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_weight_global_weight_out.thread_weight_global_weight_out), message, offset);
}

void __po_hi_marshall_request_thread_height_height_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_height_global_height_in.thread_height_global_height_in, message, offset);
}

void __po_hi_unmarshall_request_thread_height_height_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_height_global_height_in.thread_height_global_height_in), message, offset);
}

void __po_hi_marshall_request_thread_height_height_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_height_global_height_out.thread_height_global_height_out, message, offset);
}

void __po_hi_unmarshall_request_thread_height_height_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_height_global_height_out.thread_height_global_height_out), message, offset);
}

void __po_hi_marshall_request_thread_rotor_rotor_power_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_rotor_global_rotor_power_in.thread_rotor_global_rotor_power_in, message, offset);
}

void __po_hi_unmarshall_request_thread_rotor_rotor_power_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_rotor_global_rotor_power_in.thread_rotor_global_rotor_power_in), message, offset);
}

void __po_hi_marshall_request_thread_rotor_rotor_power_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_rotor_global_rotor_power_out.thread_rotor_global_rotor_power_out, message, offset);
}

void __po_hi_unmarshall_request_thread_rotor_rotor_power_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_rotor_global_rotor_power_out.thread_rotor_global_rotor_power_out), message, offset);
}

void __po_hi_marshall_request_thread_gps_location_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_gps_global_location_in.thread_gps_global_location_in, message, offset);
}

void __po_hi_unmarshall_request_thread_gps_location_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_gps_global_location_in.thread_gps_global_location_in), message, offset);
}

void __po_hi_marshall_request_thread_gps_location_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_gps_global_location_out.thread_gps_global_location_out, message, offset);
}

void __po_hi_unmarshall_request_thread_gps_location_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_gps_global_location_out.thread_gps_global_location_out), message, offset);
}

void __po_hi_marshall_request_thread_set_target_new_target_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_set_target_global_new_target_in.thread_set_target_global_new_target_in, message, offset);
}

void __po_hi_unmarshall_request_thread_set_target_new_target_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_set_target_global_new_target_in.thread_set_target_global_new_target_in), message, offset);
}

void __po_hi_marshall_request_thread_set_target_new_target_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_set_target_global_new_target_out.thread_set_target_global_new_target_out, message, offset);
}

void __po_hi_unmarshall_request_thread_set_target_new_target_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_set_target_global_new_target_out.thread_set_target_global_new_target_out), message, offset);
}

void __po_hi_marshall_request_thread_analyse_data_location_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_analyse_data_global_location_in.thread_analyse_data_global_location_in, message, offset);
}

void __po_hi_unmarshall_request_thread_analyse_data_location_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_analyse_data_global_location_in.thread_analyse_data_global_location_in), message, offset);
}

void __po_hi_marshall_request_thread_analyse_data_height_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_analyse_data_global_height_in.thread_analyse_data_global_height_in, message, offset);
}

void __po_hi_unmarshall_request_thread_analyse_data_height_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_analyse_data_global_height_in.thread_analyse_data_global_height_in), message, offset);
}

void __po_hi_marshall_request_thread_analyse_data_weight_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_analyse_data_global_weight_in.thread_analyse_data_global_weight_in, message, offset);
}

void __po_hi_unmarshall_request_thread_analyse_data_weight_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_analyse_data_global_weight_in.thread_analyse_data_global_weight_in), message, offset);
}

void __po_hi_marshall_request_thread_analyse_data_rotor_power_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_analyse_data_global_rotor_power_out.thread_analyse_data_global_rotor_power_out, message, offset);
}

void __po_hi_unmarshall_request_thread_analyse_data_rotor_power_out 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_analyse_data_global_rotor_power_out.thread_analyse_data_global_rotor_power_out), message, offset);
}

void __po_hi_marshall_request_thread_analyse_data_rotor_power_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_analyse_data_global_rotor_power_in.thread_analyse_data_global_rotor_power_in, message, offset);
}

void __po_hi_unmarshall_request_thread_analyse_data_rotor_power_in 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_analyse_data_global_rotor_power_in.thread_analyse_data_global_rotor_power_in), message, offset);
}

void __po_hi_marshall_request_thread_analyse_data_new_target 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_float (request->vars.thread_analyse_data_global_new_target.thread_analyse_data_global_new_target, message, offset);
}

void __po_hi_unmarshall_request_thread_analyse_data_new_target 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_float (&(request->vars.thread_analyse_data_global_new_target.thread_analyse_data_global_new_target), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case thread_weight_global_weight_in:
    {
      __po_hi_marshall_request_thread_weight_weight_in (request, message, &(offset));

      break;
    }
    case thread_weight_global_weight_out:
    {
      __po_hi_marshall_request_thread_weight_weight_out (request, message, &(offset));

      break;
    }
    case thread_height_global_height_in:
    {
      __po_hi_marshall_request_thread_height_height_in (request, message, &(offset));

      break;
    }
    case thread_height_global_height_out:
    {
      __po_hi_marshall_request_thread_height_height_out (request, message, &(offset));

      break;
    }
    case thread_rotor_global_rotor_power_in:
    {
      __po_hi_marshall_request_thread_rotor_rotor_power_in (request, message, &(offset));

      break;
    }
    case thread_rotor_global_rotor_power_out:
    {
      __po_hi_marshall_request_thread_rotor_rotor_power_out (request, message, &(offset));

      break;
    }
    case thread_gps_global_location_in:
    {
      __po_hi_marshall_request_thread_gps_location_in (request, message, &(offset));

      break;
    }
    case thread_gps_global_location_out:
    {
      __po_hi_marshall_request_thread_gps_location_out (request, message, &(offset));

      break;
    }
    case thread_set_target_global_new_target_in:
    {
      __po_hi_marshall_request_thread_set_target_new_target_in (request, message, &(offset));

      break;
    }
    case thread_set_target_global_new_target_out:
    {
      __po_hi_marshall_request_thread_set_target_new_target_out (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_location_in:
    {
      __po_hi_marshall_request_thread_analyse_data_location_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_height_in:
    {
      __po_hi_marshall_request_thread_analyse_data_height_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_weight_in:
    {
      __po_hi_marshall_request_thread_analyse_data_weight_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_rotor_power_out:
    {
      __po_hi_marshall_request_thread_analyse_data_rotor_power_out (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_rotor_power_in:
    {
      __po_hi_marshall_request_thread_analyse_data_rotor_power_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_new_target:
    {
      __po_hi_marshall_request_thread_analyse_data_new_target (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case thread_weight_global_weight_in:
    {
      __po_hi_unmarshall_request_thread_weight_weight_in (request, message, &(offset));

      break;
    }
    case thread_weight_global_weight_out:
    {
      __po_hi_unmarshall_request_thread_weight_weight_out (request, message, &(offset));

      break;
    }
    case thread_height_global_height_in:
    {
      __po_hi_unmarshall_request_thread_height_height_in (request, message, &(offset));

      break;
    }
    case thread_height_global_height_out:
    {
      __po_hi_unmarshall_request_thread_height_height_out (request, message, &(offset));

      break;
    }
    case thread_rotor_global_rotor_power_in:
    {
      __po_hi_unmarshall_request_thread_rotor_rotor_power_in (request, message, &(offset));

      break;
    }
    case thread_rotor_global_rotor_power_out:
    {
      __po_hi_unmarshall_request_thread_rotor_rotor_power_out (request, message, &(offset));

      break;
    }
    case thread_gps_global_location_in:
    {
      __po_hi_unmarshall_request_thread_gps_location_in (request, message, &(offset));

      break;
    }
    case thread_gps_global_location_out:
    {
      __po_hi_unmarshall_request_thread_gps_location_out (request, message, &(offset));

      break;
    }
    case thread_set_target_global_new_target_in:
    {
      __po_hi_unmarshall_request_thread_set_target_new_target_in (request, message, &(offset));

      break;
    }
    case thread_set_target_global_new_target_out:
    {
      __po_hi_unmarshall_request_thread_set_target_new_target_out (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_location_in:
    {
      __po_hi_unmarshall_request_thread_analyse_data_location_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_height_in:
    {
      __po_hi_unmarshall_request_thread_analyse_data_height_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_weight_in:
    {
      __po_hi_unmarshall_request_thread_analyse_data_weight_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_rotor_power_out:
    {
      __po_hi_unmarshall_request_thread_analyse_data_rotor_power_out (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_rotor_power_in:
    {
      __po_hi_unmarshall_request_thread_analyse_data_rotor_power_in (request, message, &(offset));

      break;
    }
    case thread_analyse_data_global_new_target:
    {
      __po_hi_unmarshall_request_thread_analyse_data_new_target (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


