#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"thread_weight_global_weight_in","thread_weight_global_weight_out","thread_height_global_height_in","thread_height_global_height_out","thread_rotor_global_rotor_power_in","thread_rotor_global_rotor_power_out","thread_radar_global_blockade_in","thread_radar_global_blockade_out","thread_gps_global_location_in","thread_gps_global_location_out","thread_set_target_global_new_target_in","thread_set_target_global_new_target_out","thread_analyse_data_global_location_in","thread_analyse_data_global_height_in","thread_analyse_data_global_weight_in","thread_analyse_data_global_rotor_power_out","thread_analyse_data_global_rotor_power_in","thread_analyse_data_global_blockade_in","thread_analyse_data_global_status_change","thread_analyse_data_global_new_target"};

